### ISSUE TITLE
Add Rust Performance Data

### ISSUE THREAD

**Issue by sc0ttwad3** [alexhultman/Node.js-needs-to-die-in-a-fire-and-Golang-is-the-perfect-arsonist#1]
Similar to what is compared: __Node.js__ then __Node.js/Express.js__; maybe, a comparison of __Rust__ then __Rust/Iron__ or other added to the table of performance data.

**Comment by louisgv** [comment]
:+1:

**Comment by alexhultman** [comment]
No. I think you missed the point here. Obviously C/C++/Rust are one leap past golang in performance, that goes without saying.  The point is that golang is the perfect compromize.

The reason why languages like C++ and Rust have no real usage share in back-end is because they lack any enforced networking design. Node.js has a very strict and limited design (callbacks only, enforced to libuv). golang also has a very strict and limited design with the runtime managing goroutines.

C++ and Rust have no enforced event system, that's why you get a big mess of different systems interfering when you mix. MongoDB client has one event system, Redis has one. That is the strength and weakness of having no enforcement and also the reason why these languages never will become widely used for back-end.

**Comment by sc0ttwad3** [comment]
I did miss that distinction in what you were going toward: a compromise midpoint in the spectrum. Thanks for the clarification. I'll close this out.
