### ISSUE TITLE
rejected: invalid

### ISSUE THREAD

**Issue by geogeim** [alexhultman/Node.js-needs-to-die-in-a-fire-and-Golang-is-the-perfect-arsonist#4]
this is the same discussion that was happening 15 years ago with java, and java easily won over c++. same with node js. it's not performance that counted, it's because the ease of use encouraged people to make node the most vibrant software ecosystem to date. node won, no matter how many benchmarks you make. but hey, webassembly is taking off so who knows what will be the future. 
ps. i'm a c++ guy

**Comment by alexhultman** [comment]
Well yeah, obviously the back-end industry doesn't prioritize performance simply because you "scale out" via paying for more hardware to solve your performance problems (even Ruby on Rails can be used successfully). And yes, ease of use is priority 1 in back-end, I'm well aware. The idea here is that I'm passively looking at the industry and can see a change happening where people are using Swift, Go and such languages more and more and I approve of this. That's all there is to this. I'm well aware of flame wars this and flame wars that. This is just my experience with Nodesters and my opinion of the industry. Also, it is hard to argue that Node.js would be any more "easy-to-use" than golang as an example, they both tick the same way basically.

**Comment by alexhultman** [comment]
If you compare the back-end industry with the gaming industry as an example, it is completely different. In the gaming industry you have a very strict hardware target to squeeze those pretty graphics out of and the more graphics you can get in, the more you sell. Back-end has no such constraint because you simply deploy whatever garbage you have written and as long as it works (and it doesn't even have to work well, it just has to not crash for 1 hour) then you are in the clear because you have auto-restarts and such that manages your incompetence automatically for you.

**Comment by geogeim** [comment]
well, i agree with all that you said, i'm just saying that you argue for the one percent, for which performance matters. i would really like to read about how much easier it is to express yourself in go than in js (it wouldn't even be that hard). otherwise i can pull out my assembler-fu and declare all languages inferior, but i doubt that anyone would take me seriously :)

**Comment by alexhultman** [comment]
The problem I have with the back-end industry is that it is the most delirious software industry there is. It doesn't recognize its own incompetence but instead believes fully it is some kind of brain surgery business where you need to wear a white robe and have glasses at the very end of your nose tip to make it. It really is the lowest of the low when it comes to programming. You can basically pull down your pants and take a shit on the desk and be done with your day.

* It is the only industry which *claims* performance is important (marketing up your asshole, everywhere you look).
* It is the only industry in which performance doesn't matter *one single bit* (Sails.js and Hapi perform as the same level as Ruby on Rails and nobody even noticed).

You see this *everywhere* in the marketing. Why was Node.js ever designed? Performance. Every single initial presentation of Node.js talk about performance this and performance that and it is also the primary marketing today:

> Node.js® is a JavaScript runtime built on Chrome's V8 JavaScript engine. Node.js uses an event-driven, non-blocking I/O model that makes it lightweight and efficient. Node.js' package ecosystem, npm, is the largest ecosystem of open source libraries in the world.

More like, "Node.js is easy to use and since you don't care what shit you deploy, neither do we. We spent $9 mil on marketing though so go get yourself a t-shirt". It really is the worst piece of shit ever designed.

**Comment by aichholzer** [comment]
Well said @alexhultman!
👍🏻👍🏻👍🏻

Despite being a Nodester myself, I can only agree with you, completely!
Just as you, I started with C++, then got interested in the web which lead me to PHP -in 1996 (with some luck I managed to stay away from Ruby) and eventually I landed at Node. Just like PHP, Node's popularity only exploded because of it's easiness and because -indeed- no one cares for CPU usage as long as you can pay the costs, even more with services like AWS charging a penny for them.

I mainly make my living programming for the web, but I love this remark:

> It doesn't recognize its own incompetence but instead believes fully it is some kind of brain surgery business where you need to wear a white robe and have glasses at the very end of your nose tip to make it. It really is the lowest of the low when it comes to programming.

I like to think of the concept of `web programming` as IT's whore; every idiot who has just watched a tutorial here and there or read some cheap tutorials, immediately becomes a `web developer` and you can't even begin to imagine the amount of crap being deployed, left right and center.

> An engineer who builds a bridge has the responsibility to make sure the damn bridge does it's job right, if the bridge collapses it's the end of his career, no two ways about it. On the other hand, if a `web development engineer` takes down an entire system because he has no idea of what he is writing, then it's easy to blame it on the "bugs" or just ask for more CPU.

Ultimately, Node is just another tool, one to make things easier and to get companies to deploy their stuff faster. You can't really blame Node for what it is, there are plenty of crappy C++ developers around as well. If you are offered a pile of dirt for dinner, you eat it and you get sick, you can't really blame it on the dirt, can you?

**Comment by geogeim** [comment]
Ha haha ha, remember this is the industry that stated with cgi scripts and then moved onto php.

**Comment by geogeim** [comment]
People have results with it despite of it's flaws. The whole point is "keep it simple, stupid" because no matter how much we geek about cool programming ideas and techniques writing correct software is hard, really really hard. Just look at what they did: they took a javascript engine, a language with huge mindshare on the client side for historical reasons, and they bolted it onto a "event loop" basically windows 3.x cooperative multitasking model. Simple and stupid and it worked, people rushed to use it and they had success with it because it drastically lowered the bar of server side programming. You no longer had to worry about state modifying from under you, a huge problem with multithreading in Java, and with server side programming in general. Stop dismissing people that use it as being inherently stupid, and start looking at how fast you can bootstrap a simple web app comparing to other languages starting from scratch, learning the language and the tools. For me it was child play and then I understood how good this is for rapid prototyping. Yes i would think twice for using it in large enterprise apps, but for the 99% of people who need limited functionality it just works. And no client wants to pay the price of engineering the hell out of a stupid ecommerce website.

**Comment by aichholzer** [comment]
> For me it was child play and then I understood how good this is for rapid prototyping.

@geogeim 👍🏻

**Comment by gjuchault** [comment]
> it's because the ease of use encouraged people to make node the most vibrant software ecosystem to date

Ease-of-use is shitty when we start talking about debugging and profiling compared to what you have in a compiled environment

**Comment by krnaveen14** [comment]
> Simple and stupid and it worked, people rushed to use it and they had success with it because it drastically lowered the bar of server side programming. You no longer had to worry about state modifying from under you, a huge problem with multithreading in Java, and with server side programming in general

Really..? You mean Really...!!? How much expertise are you having in that scope? All I can think of is you don't even know what you're talking about..!

**Comment by alexhultman** [comment]
> Stop dismissing people that use it as being inherently stupid, and start looking at how fast you can bootstrap a simple web app comparing to other languages starting from scratch, learning the language and the tools.

The problem here is that we still assume that Node.js is more easy to use than for instance golang. It is not. Look at golang it doesn't even expose callbacks to the programmer but manages all of that under the hood. It basically is like async/await only it is implicit. The fact why I think Node.js is so inferior is simply because yo can do prototyping at the exact same productivity in golang it literally is the same shit, only 10x faster:

```
http.HandleFunc("/", func (w http.ResponseWriter, r *http.Request) {
  w.Write("Some shitty content here");
});
```

One would really need to perform some serious mind gymnastics to claim this is "less productive" than Node.js.

**Comment by aichholzer** [comment]
@alexhultman without a doubt, Go is better tech than Node, but Javascript has simply been around for longer, there are more resources and it's learning curve is milder. As I said before, I agree with you, but you need to take into account the inherent laziness that exists within every human being.
Having said that, this:

```
app.get('/', (req, res) => {
  res.send('Some shitty content here');
});
```
is smaller than your Go example, and in the end only that is what matters.

**Comment by alexhultman** [comment]
@aichholzer Hehe, wtf that argument is like saying as a secretary "I can only write English with comic sans, if you as a company use any other font then I'm completely lost".

**Comment by aichholzer** [comment]
@alexhultman no, it's more like saying I can only use Word, so if you use Pages I am lost... And there are plenty of secretaries around that can only use Word. Your font example, is a level of granularity that is not comparable with the language itself, but more with something like using promises or callbacks, which is a whole different subject.

**Comment by alexhultman** [comment]
How do these people even manage to live day by day? Who feeds them?

**Comment by aichholzer** [comment]
@alexhultman 
>  It also implies that you as a developer write miles and miles of source code each day and need to write as few characters as possible...

I was merely trying to make a point as to why Node has gained so much popularity. The average `developer` will want to write as little as possible. `Web programming` has become all about "write less & do more"

**Comment by geogeim** [comment]
@alexhultman
> One would really need to perform some serious mind gymnastics to claim this is "less productive" than Node.js. And this is exactly why I think golang is the better tech to use because it balances productivity with performance.

I never implied that node is better than go, i simply don't have enough experience with go

> How do these people even manage to live day by day? Who feeds them?

Probably dudes who post clickbaity titles like "Node.js needs to die in a fire and Golang is the perfect arsonist" and who calls people who use such and such tool as "zombies"

**Comment by alexhultman** [comment]
@geogeim Well you clicked, didn't you? :wink: HackerNews is all about the title -> had it not been flagged by SJW pussies it would have trended like crazy I'm sure. HN is not a place for negativity though, as the slightest negativity or critical thinking will result in the ol' flag/censor/ban treatment. :stuck_out_tongue_winking_eye:

**Comment by luispcosta** [comment]
> @geogeim Well you clicked, didn't you? 😉 HackerNews is all about the title -> had it not been flagged by SJW pussies it would have trended like crazy I'm sure. HN is not a place for negativity though, as the slightest negativity or critical thinking will result in the ol' flag/censor/ban treatment. 😜

My god you're such a douchebag. Hackernews bans and flags people who, like you, dismiss everyone else's opinions, calling people "pussies", who can't see both sides of arguments and is blind to any opinion that doesn't match their own. To be honest, people like you should not have a place in tech.

And I'm not talking about why Node is better or worse. You've brought the discussion into a whole new level. Why can't you simply understand that people have different ways to do things? Just because one technology is faster than the other, that doesn't mean that it has to replace every new approach in new projects. 

Let technology evolve on its own. Different approaches and solutions appear over time. Stop being so blind and simple minded. 

I would say you'd need to get out of your hole and experience new things. You have nothing to add to the community other than bashing everyone who doesn't share your opinions, keep it to your self. If you don't want to accept new approaches and ways to do things, good, don't. No one is forcing you to. 

Think about what value you can provide to the community. This is not bringing any value to anyone.

**Comment by alexhultman** [comment]
@luispcosta Clearly you didn't read this post. I do C++. C++ is what I do. My post is celebrating the spreadth of Golang. Golang is not C++. This post is not just about me, even though it orbits around my experiences. This post is about celebrating new, better tech. Tech that doesn't force us to rape the earth with excessive amount of coal power plants just to keep up with all the retardation we create by shoving horse shit in our computers. Besides, I don't see how you have helped this industry any more than I have.

**Comment by johannesjo** [comment]
Wow. I'm amazed how much arrogance is present here. If you rant about how bad node is, then just don't use it. To me being a good programmer means also to be able to understand that there are always things worth considering beyond your own narrow perspective and that other approaches have their own advantages, even if you are not fond of them personally.

**Comment by gfviegas** [comment]
Just a quick reminder:

Even though you present me a language or framework or some shit that can handle 5000% more requests per second than node maybe I just don't need that. Maybe programming in node is more pleasant. Maybe I just need to handle 1k requests per second. Maybe I'm fine with that.

There's nothing wrong on node performing poorly compared with other thecs. The same goes to Apache, php, RoR and etc. There's other aspects that node (and all these "shitty" techs) are superb and you just ignored it. Of course you mentioned it here in this issue, but...

It's so arrogant to say "this tech must die because there's another which performs waaaaay better". Seriously.
