### ISSUE TITLE
Rust?

### ISSUE THREAD

**Issue by iSynaptic** [alexhultman/Node.js-needs-to-die-in-a-fire-and-Golang-is-the-perfect-arsonist#7]
Alex - Loved this post! Had the exact same experiences.

I'm curious, what are your thoughts on the [Rust language](https://www.rust-lang.org/en-US/)?

**Comment by alexhultman** [comment]
Great.

#1 <- golang has a strict runtime with enforced networking and eventing design so that every module plays well together just like Node.js. C++ and Rust lack this (thankfully!) which makes it hard to piece together a MongoDB driver with a Redis driver without adding messed up threading and shit.
